### PR TITLE
Blukon bugs fixing and improvements

### PR DESCRIPTION
**Pull request by gregorybel**
- should fix issue when collector is being restarted during backfilling
- decode serial only every 12 hours
- remove dead code
- send blukon to sleep after error and after sensor bad state
- clean and reformat code
- allow decoding during starting period

successfully tested.

### CODE REVIEW

**Comment by gregorybel** [comment]
@keencave thanks for feedback. Regarding issue (if there is an issue), this is not related to PR so I would suggest to write an issue for this. Are you sure your code to be decode sensor state is correct? 

Review from PR should be related to the modifications and I did not modify something related to "expired" state.

**Comment by keencave** [comment]
Sorry, I dont want to mix issues. You are right, the sensor state is a new issue. I will make an input on this.
Your PR seems to be well done and OK. I will do my test with your changes next week.

**Comment by jamorham** [comment]
Is this ready to be merged?

**Comment by gregorybel** [comment]
Yes it is.

**Pull request merged**
