### PR TITLE
Blukon: reject new values coming before 4min

### PR DESCRIPTION
**Pull request by gregorybel**
Somehow, sometimes values are sent from blukon earlier than 5min and we get capture rate bigger than 100% (often even >110%).
For peaple looping, AMA algo is expecting values every 5min and it is not recommanded to use other interval (not tested).
This PR workaround the problem.

Based on idea from @keencave 

Successfully tested!

### CODE REVIEW

**Comment by keencave** [comment]
We should add this. Code looks good.

**Comment by gregorybel** [comment]
@jamorham any questions or concerns? If not can we merge?

**Comment by jamorham** [comment]
I'm not sure I even knew this PR was here but if you guys think this looks good then I am happy to merge it.

From a code perspective you can use helpers like:

` m_minutesDiffToLastReading = (int) (JoH.msSince(m_persistentTimeLastBg) / Constants.MINUTE_IN_MS);`

To improve readability and reduce the chance of errors with misplaced brackets etc. You can simplify it further by statically importing the helpers to remove the qualifiers like `JoH` and `Constants`

**Comment by gregorybel** [comment]
@jamorham  thanks and will next time use your suggestion, look really better

**Pull request merged**
