### PR TITLE
Adding tests for Forecast.java

### PR DESCRIPTION
**Pull request by ahaarrestad**
Added some tests to get to know the code-base. 

- Added Google Truth as assertion framework for tests. (http://google.github.io/truth/)
- Added tests for Forecast.java (and subclasses)
- Minor refactoring to Forecast.java after tests were green
  * Removed redundant 'public' from interface
  * Formatted code
  * Changed parameter in toPrimitiveFromList to receive 'Collection' instead of 'List'

@jamorham : Code builds green in my fork, but build seems to be a bit unstable. I'll look into this next. Please look through this pullrequest and let me know if it conforms to the contributing guidelines or if you want me to adjust it.

### CODE REVIEW

**Comment by jamorham** [comment]
Hi, thanks for this. Can you describe in a little more detail the changes made in `Forecast.java` ?

Thanks. Jon

**Comment by ahaarrestad** [comment]
@jamorham I've updated the initial comment with the changes to Forecast.java

**Comment by jamorham** [comment]
Ok so the change to `Forecast.java` is just automatic white space reformatting and the change to Collection to allow using `toArray` to reduce code duplication?

**Comment by ahaarrestad** [comment]
The changes to Forecast.java are as you commented.

**Pull request merged**
