### PR TITLE
cleaned update charts methods, for timebuttons not to be interfered

### PR DESCRIPTION
**Pull request by RaabenFuchs**
In combinatioin with the timebuttons, i tried to improve functionality and tydie things up a bit.

reason is, that buttons didn't really work on my phone (android6), view always switched back on every screenupdate...

working principles should remain the same, with structurizing it to
- **setupChart()** and
- **updateChart()** method

i just copied and deleted fragments here and there

### CODE REVIEW

**Comment by RaabenFuchs** [comment]
Hi, I want to add that i'm new to java/android, but it really feals like c++. So i'm not gonna enhance things, but would really love to contribute and learn some stuff here.
I also took a look at the gitter chat, is it necessary to discuss things there before commit? Or is there any other forum?
Really love the app, but some things are still a bit confusing. And what is really funny, that i just discovered the daydream feature by reading the code... which looks really cool

Hopefully more peaple are going to use xdrip+ keep up the good work! cheers

**Comment by jamorham** [comment]
Hi there,

Can you explain the issue these changes are designed to address? Thanks.

**Comment by RaabenFuchs** [comment]
Yes, sry. 
The problem was, that the chart always, under any circumstance occasionally resized.
This was caused by many resets of the chart Viewports:

 holdViewport.set(0, 0, 0, 0);
 chart.setCurrentViewport(holdViewport);	
 previewChart.setCurrentViewport(holdViewport);

For me this is annoying, because always when the chart resizes, it changes its side-ratio. I think it's bad for therapie when the charts always automatically streches and of course the slopes appear different at any point of view.
**And also it always overwrites the setting of the 'hours' (x-axis) of the timebuttons.** which was the main reason.

Finally i've changed this option to fix the sides ratio by
` ChartZoomType = HORIZONTAL_AND_VERTICAL;       //HORIZONTAL_AND_VERTICAL or HORIZONTAL`
variable. So if you dislike you or anybody else can change this, of course.
Or i would create a preferences entry, if you prefere.

In this case i would also add a preference, to change the value of the upper and lower boundaries. I would like to have them variable, too. But i guess you maybe dont agree with that idea...

what do you think?

**Comment by RaabenFuchs** [comment]
** RY, I read the contributing.md** 
I'll behave now

**Pull request closed without merging**
