### PR TITLE
For LONG_TEXT complication, add time since last reading

### PR DESCRIPTION
**Pull request by gregorybel**
add time since last BG read, usefull for debug and anyway enough room to show it.
Successfully tested.

### CODE REVIEW

**Comment by jamorham** [comment]
Can you provide a screenshot/photo to show how this looks? thanks

**Comment by gregorybel** [comment]
you can see it in this issue: https://github.com/NightscoutFoundation/xDrip/issues/270

**Comment by jamorham** [comment]
According to the source tree this was already merged back in november last year. I'm not sure how it appears as a change set here or why it isn't in your source tree.

https://github.com/NightscoutFoundation/xDrip/commit/fe18c0d5df913c70e9d3466ba4bbf04bd926f9c8

https://github.com/jamorham/xDrip-plus/blob/627b0acd89b9a01b0422c85b77fe15cd911a0680/wear/src/main/java/com/eveningoutpost/dexdrip/Services/CustomComplicationProviderService.java#L163

**Comment by gregorybel** [comment]
really? then don't know either, need to check. then I close this pr.

**Pull request closed without merging**
