### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by jamorham**

### CODE REVIEW

**Comment by tolot27** [comment]
Please do not merge this PR! See my message on Gitter. The Crowdin Support & Dev team still investigate the issue.

**Comment by tolot27** [comment]
> Please do not merge this PR! See my message on Gitter. The Crowdin Support & Dev team still investigate the issue.

I've solved the problem. You can now safely merge this PR.

**Comment by jamorham** [comment]
It seems to fail the unit tests with a broken italian translation of a format string

```
com.eveningoutpost.dexdrip.ui.TranslationTest > testFormatStrings FAILED
    java.lang.RuntimeException: Failed expires days test with language it with exception: java.lang.IllegalArgumentException: unknown format type: scelta
        at com.eveningoutpost.dexdrip.ui.TranslationTest.testFormatStrings(TranslationTest.java:58)
```

**Comment by tolot27** [comment]
I've fixed the formatted strings. All tests passed now.

**Pull request merged**
