### PR TITLE
enable Multi-Window on supported Samsung devices

### PR DESCRIPTION
**Pull request by joshzbarta**
based on info from http://stackoverflow.com/questions/14111052/adding-samsung-multi-window-support-to-android-application

### CODE REVIEW

**Comment by jamorham** [comment]
Hi,

Thanks for this. I don't think I have a device which supports this making direct testing difficult.

Can you confirm that you have tested this yourself on a suitable samsung device? How does it change the app behavior ?

I believe that this will have no effect at all on non-samsung devices which will ignore the additional manifest items? Please let me know if you think that assumption is correct or not.

**Comment by jamorham** [comment]
What do you think about adding the pen window stuff as well:

```
<category android:name="android.intent.category.PENWINDOW_LAUNCHER" />
<meta-data android:name="com.samsung.android.sdk.multiwindow. penwindow.enable" android:value="true" />
```

Are there any negative implications of that?

**Comment by jamorham** [comment]
I haven't heard back from you, but @kskandis has been testing this and it looks good so I will merge it in and examine the implications with further testing. Thanks.

**Comment by joshzbarta** [comment]
Sorry for the late response, I've been traveling all weekend. Most of the testing I've done has been on my Galaxy Note 4 running stock Android 6.0.1. The multi-window stuff will be ignored on non-Samsung devices, though I haven't been able to test this firsthand. It seems the pen window features have been superseded by/combined with multi-window on the Note 4 and newer, though it might be worth enabling in order to cover older devices. As of Android 7 (Nougat), all of this would be made obsolete by native multi-window support https://developer.android.com/guide/topics/ui/multi-window.html

**Comment by kskandispersonal** [comment]
@joshzbarta I also tested your change on a Galaxy Note 4 and it works well.  Thanks!  However, in order to include xDrip+ in the multi-window tray (Pen Window??), I had to add the "penwindow" options (mentioned by @jamorham above) to the manifest as well.

**Pull request merged**
