### PR TITLE
strings.xml

### PR DESCRIPTION
**Pull request by pietballing**
Manual ROmanian translation for xDrip-plus/app/src/main/res/values-ro/strings-ro.xml
May update new version once tested.

PS: file needs to be renamed.

### CODE REVIEW

**Comment by jamorham** [comment]
Hi,thanks for submitting this. I am working through it and will have some more feedback but a first question.

Is it normal to write: HIPERglicemie with "HIPER" all capitalized? If I google for Romanian sites I don't see the word capitalized like this. I appreciate that it is easy to confuse "hypo" and "hyper" also in english but generally this is avoided in the app by referring to High and Low instead. Is there a reason not to do this in Romanian as well?

**Comment by pietballing** [comment]
Hi!

Actually you are right. If you need me to, I can send an edited version.

Pe 22 oct. 2016 00:08, "Jamorham" <notifications@github.com> a scris:

**Comment by jamorham** [comment]
Yes I think it would be better if HIPER was not all capitalized. I can give you some more feedback on the rest before you make that change so we can talk about the other edits at the same time. I would expect to be able to get to that early next week.

**Comment by pietballing** [comment]
Please send me your own email address so I can share my translation with
you via GTT (Google Translator Toolkit).
There you can comment on each string directly.

**Comment by pietballing** [comment]
You should have received a link.

**Comment by tolot27** [comment]
These translations are incorporated at Crowdin. Please close this PR.

**Pull request closed without merging**
