### PR TITLE
blukon - resubmit - improved backfilling and sensor usage allowed also in state expired

### PR DESCRIPTION
**Pull request by keencave**

### CODE REVIEW

**Comment by keencave** [comment]
deleted the .iml file and redone the PR. Hope I have done it in the right way.

**Comment by keencave** [comment]
arghh, dont know how to change the name of the PR - accidently it is named work in progress. Sorry.

**Comment by keencave** [comment]
OK, this should be fixed now.

**Comment by jamorham** [comment]
Okay, I am going to try to merge this. It still isn't right because your commit will delete the iml file but it isn't supposed to be part of the repository in the first place so perhaps this is a sensible course of action anyway.

**Pull request merged**
